# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly galleon plugins - Nightly WildFly 37.0.0.Final backward compatibility

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-galleon-plugins:
    name: Build test Galleon Plugins
    uses: wildfly/galleon-plugins/.github/workflows/nightly-workflow.yml@main
    with:
      wildfly-ref: 37.0.0.Final