# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: DISABLED, can re-enable for WildFly 32. WildFly galleon plugins - Nightly WildFly backward compatibility

on:
  workflow_call:
    inputs:
      wildfly-ref:
        description: "WildFly branch/tag"
        required: false
        default: "main"
        type: string
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
  test-galleon-plugins:
    name: Build test Galleon Plugins
    uses: wildfly/galleon-plugins/.github/workflows/testing-workflow.yml@main
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    with:
      wildfly-ref: ${{ inputs.wildfly-ref }}
